package com.guohe.app.model;

public class Gpa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester1
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester2
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester3
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester4
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester5
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester6
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester7
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.semester8
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String semester8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpa.average
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String average;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.uid
     *
     * @return the value of gpa.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.uid
     *
     * @param uid the value for gpa.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester1
     *
     * @return the value of gpa.semester1
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester1() {
        return semester1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester1
     *
     * @param semester1 the value for gpa.semester1
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester1(String semester1) {
        this.semester1 = semester1 == null ? null : semester1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester2
     *
     * @return the value of gpa.semester2
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester2() {
        return semester2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester2
     *
     * @param semester2 the value for gpa.semester2
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester2(String semester2) {
        this.semester2 = semester2 == null ? null : semester2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester3
     *
     * @return the value of gpa.semester3
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester3() {
        return semester3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester3
     *
     * @param semester3 the value for gpa.semester3
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester3(String semester3) {
        this.semester3 = semester3 == null ? null : semester3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester4
     *
     * @return the value of gpa.semester4
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester4() {
        return semester4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester4
     *
     * @param semester4 the value for gpa.semester4
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester4(String semester4) {
        this.semester4 = semester4 == null ? null : semester4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester5
     *
     * @return the value of gpa.semester5
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester5() {
        return semester5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester5
     *
     * @param semester5 the value for gpa.semester5
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester5(String semester5) {
        this.semester5 = semester5 == null ? null : semester5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester6
     *
     * @return the value of gpa.semester6
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester6() {
        return semester6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester6
     *
     * @param semester6 the value for gpa.semester6
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester6(String semester6) {
        this.semester6 = semester6 == null ? null : semester6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester7
     *
     * @return the value of gpa.semester7
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester7() {
        return semester7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester7
     *
     * @param semester7 the value for gpa.semester7
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester7(String semester7) {
        this.semester7 = semester7 == null ? null : semester7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.semester8
     *
     * @return the value of gpa.semester8
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getSemester8() {
        return semester8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.semester8
     *
     * @param semester8 the value for gpa.semester8
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setSemester8(String semester8) {
        this.semester8 = semester8 == null ? null : semester8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpa.average
     *
     * @return the value of gpa.average
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpa.average
     *
     * @param average the value for gpa.average
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setAverage(String average) {
        this.average = average == null ? null : average.trim();
    }
}