package com.guohe.app.model;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.startSemester
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String startsemester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.credit
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.examinationMethod
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String examinationmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseAttribute
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String courseattribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.alternativeCourseNumber
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String alternativecoursenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.alternativeCourseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String alternativecoursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.markOfScore
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    private String markofscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.uid
     *
     * @return the value of score.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.uid
     *
     * @param uid the value for score.uid
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.startSemester
     *
     * @return the value of score.startSemester
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getStartsemester() {
        return startsemester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.startSemester
     *
     * @param startsemester the value for score.startSemester
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setStartsemester(String startsemester) {
        this.startsemester = startsemester == null ? null : startsemester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseName
     *
     * @return the value of score.courseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseName
     *
     * @param coursename the value for score.courseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.credit
     *
     * @return the value of score.credit
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.credit
     *
     * @param credit the value for score.credit
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.examinationMethod
     *
     * @return the value of score.examinationMethod
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getExaminationmethod() {
        return examinationmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.examinationMethod
     *
     * @param examinationmethod the value for score.examinationMethod
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setExaminationmethod(String examinationmethod) {
        this.examinationmethod = examinationmethod == null ? null : examinationmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseAttribute
     *
     * @return the value of score.courseAttribute
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getCourseattribute() {
        return courseattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseAttribute
     *
     * @param courseattribute the value for score.courseAttribute
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setCourseattribute(String courseattribute) {
        this.courseattribute = courseattribute == null ? null : courseattribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.alternativeCourseNumber
     *
     * @return the value of score.alternativeCourseNumber
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getAlternativecoursenumber() {
        return alternativecoursenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.alternativeCourseNumber
     *
     * @param alternativecoursenumber the value for score.alternativeCourseNumber
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setAlternativecoursenumber(String alternativecoursenumber) {
        this.alternativecoursenumber = alternativecoursenumber == null ? null : alternativecoursenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.alternativeCourseName
     *
     * @return the value of score.alternativeCourseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getAlternativecoursename() {
        return alternativecoursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.alternativeCourseName
     *
     * @param alternativecoursename the value for score.alternativeCourseName
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setAlternativecoursename(String alternativecoursename) {
        this.alternativecoursename = alternativecoursename == null ? null : alternativecoursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.markOfScore
     *
     * @return the value of score.markOfScore
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getMarkofscore() {
        return markofscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.markOfScore
     *
     * @param markofscore the value for score.markOfScore
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setMarkofscore(String markofscore) {
        this.markofscore = markofscore == null ? null : markofscore.trim();
    }
}