package com.guohe.app.model;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.startSemester
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String startSemester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.credit
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.examinationMethod
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String examinationMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseAttribute
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String courseAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.alternativeCourseNumber
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String alternativeCourseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.alternativeCourseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String alternativeCourseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.markOfScore
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String markOfScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.uid
     *
     * @return the value of score.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.uid
     *
     * @param uid the value for score.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.startSemester
     *
     * @return the value of score.startSemester
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getStartSemester() {
        return startSemester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.startSemester
     *
     * @param startSemester the value for score.startSemester
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setStartSemester(String startSemester) {
        this.startSemester = startSemester == null ? null : startSemester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseName
     *
     * @return the value of score.courseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseName
     *
     * @param courseName the value for score.courseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.credit
     *
     * @return the value of score.credit
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.credit
     *
     * @param credit the value for score.credit
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.examinationMethod
     *
     * @return the value of score.examinationMethod
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getExaminationMethod() {
        return examinationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.examinationMethod
     *
     * @param examinationMethod the value for score.examinationMethod
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setExaminationMethod(String examinationMethod) {
        this.examinationMethod = examinationMethod == null ? null : examinationMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseAttribute
     *
     * @return the value of score.courseAttribute
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getCourseAttribute() {
        return courseAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseAttribute
     *
     * @param courseAttribute the value for score.courseAttribute
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setCourseAttribute(String courseAttribute) {
        this.courseAttribute = courseAttribute == null ? null : courseAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.alternativeCourseNumber
     *
     * @return the value of score.alternativeCourseNumber
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getAlternativeCourseNumber() {
        return alternativeCourseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.alternativeCourseNumber
     *
     * @param alternativeCourseNumber the value for score.alternativeCourseNumber
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setAlternativeCourseNumber(String alternativeCourseNumber) {
        this.alternativeCourseNumber = alternativeCourseNumber == null ? null : alternativeCourseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.alternativeCourseName
     *
     * @return the value of score.alternativeCourseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getAlternativeCourseName() {
        return alternativeCourseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.alternativeCourseName
     *
     * @param alternativeCourseName the value for score.alternativeCourseName
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setAlternativeCourseName(String alternativeCourseName) {
        this.alternativeCourseName = alternativeCourseName == null ? null : alternativeCourseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.markOfScore
     *
     * @return the value of score.markOfScore
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getMarkOfScore() {
        return markOfScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.markOfScore
     *
     * @param markOfScore the value for score.markOfScore
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setMarkOfScore(String markOfScore) {
        this.markOfScore = markOfScore == null ? null : markOfScore.trim();
    }
}