package com.guohe.app.model;

import java.util.ArrayList;
import java.util.List;

public class ScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public ScoreExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andStartsemesterIsNull() {
            addCriterion("startSemester is null");
            return (Criteria) this;
        }

        public Criteria andStartsemesterIsNotNull() {
            addCriterion("startSemester is not null");
            return (Criteria) this;
        }

        public Criteria andStartsemesterEqualTo(String value) {
            addCriterion("startSemester =", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterNotEqualTo(String value) {
            addCriterion("startSemester <>", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterGreaterThan(String value) {
            addCriterion("startSemester >", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterGreaterThanOrEqualTo(String value) {
            addCriterion("startSemester >=", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterLessThan(String value) {
            addCriterion("startSemester <", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterLessThanOrEqualTo(String value) {
            addCriterion("startSemester <=", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterLike(String value) {
            addCriterion("startSemester like", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterNotLike(String value) {
            addCriterion("startSemester not like", value, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterIn(List<String> values) {
            addCriterion("startSemester in", values, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterNotIn(List<String> values) {
            addCriterion("startSemester not in", values, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterBetween(String value1, String value2) {
            addCriterion("startSemester between", value1, value2, "startsemester");
            return (Criteria) this;
        }

        public Criteria andStartsemesterNotBetween(String value1, String value2) {
            addCriterion("startSemester not between", value1, value2, "startsemester");
            return (Criteria) this;
        }

        public Criteria andCoursenameIsNull() {
            addCriterion("courseName is null");
            return (Criteria) this;
        }

        public Criteria andCoursenameIsNotNull() {
            addCriterion("courseName is not null");
            return (Criteria) this;
        }

        public Criteria andCoursenameEqualTo(String value) {
            addCriterion("courseName =", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameNotEqualTo(String value) {
            addCriterion("courseName <>", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameGreaterThan(String value) {
            addCriterion("courseName >", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameGreaterThanOrEqualTo(String value) {
            addCriterion("courseName >=", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameLessThan(String value) {
            addCriterion("courseName <", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameLessThanOrEqualTo(String value) {
            addCriterion("courseName <=", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameLike(String value) {
            addCriterion("courseName like", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameNotLike(String value) {
            addCriterion("courseName not like", value, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameIn(List<String> values) {
            addCriterion("courseName in", values, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameNotIn(List<String> values) {
            addCriterion("courseName not in", values, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameBetween(String value1, String value2) {
            addCriterion("courseName between", value1, value2, "coursename");
            return (Criteria) this;
        }

        public Criteria andCoursenameNotBetween(String value1, String value2) {
            addCriterion("courseName not between", value1, value2, "coursename");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andCreditIsNull() {
            addCriterion("credit is null");
            return (Criteria) this;
        }

        public Criteria andCreditIsNotNull() {
            addCriterion("credit is not null");
            return (Criteria) this;
        }

        public Criteria andCreditEqualTo(String value) {
            addCriterion("credit =", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotEqualTo(String value) {
            addCriterion("credit <>", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThan(String value) {
            addCriterion("credit >", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThanOrEqualTo(String value) {
            addCriterion("credit >=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThan(String value) {
            addCriterion("credit <", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThanOrEqualTo(String value) {
            addCriterion("credit <=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLike(String value) {
            addCriterion("credit like", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotLike(String value) {
            addCriterion("credit not like", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditIn(List<String> values) {
            addCriterion("credit in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotIn(List<String> values) {
            addCriterion("credit not in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditBetween(String value1, String value2) {
            addCriterion("credit between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotBetween(String value1, String value2) {
            addCriterion("credit not between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodIsNull() {
            addCriterion("examinationMethod is null");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodIsNotNull() {
            addCriterion("examinationMethod is not null");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodEqualTo(String value) {
            addCriterion("examinationMethod =", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodNotEqualTo(String value) {
            addCriterion("examinationMethod <>", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodGreaterThan(String value) {
            addCriterion("examinationMethod >", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodGreaterThanOrEqualTo(String value) {
            addCriterion("examinationMethod >=", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodLessThan(String value) {
            addCriterion("examinationMethod <", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodLessThanOrEqualTo(String value) {
            addCriterion("examinationMethod <=", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodLike(String value) {
            addCriterion("examinationMethod like", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodNotLike(String value) {
            addCriterion("examinationMethod not like", value, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodIn(List<String> values) {
            addCriterion("examinationMethod in", values, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodNotIn(List<String> values) {
            addCriterion("examinationMethod not in", values, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodBetween(String value1, String value2) {
            addCriterion("examinationMethod between", value1, value2, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andExaminationmethodNotBetween(String value1, String value2) {
            addCriterion("examinationMethod not between", value1, value2, "examinationmethod");
            return (Criteria) this;
        }

        public Criteria andCourseattributeIsNull() {
            addCriterion("courseAttribute is null");
            return (Criteria) this;
        }

        public Criteria andCourseattributeIsNotNull() {
            addCriterion("courseAttribute is not null");
            return (Criteria) this;
        }

        public Criteria andCourseattributeEqualTo(String value) {
            addCriterion("courseAttribute =", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeNotEqualTo(String value) {
            addCriterion("courseAttribute <>", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeGreaterThan(String value) {
            addCriterion("courseAttribute >", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeGreaterThanOrEqualTo(String value) {
            addCriterion("courseAttribute >=", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeLessThan(String value) {
            addCriterion("courseAttribute <", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeLessThanOrEqualTo(String value) {
            addCriterion("courseAttribute <=", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeLike(String value) {
            addCriterion("courseAttribute like", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeNotLike(String value) {
            addCriterion("courseAttribute not like", value, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeIn(List<String> values) {
            addCriterion("courseAttribute in", values, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeNotIn(List<String> values) {
            addCriterion("courseAttribute not in", values, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeBetween(String value1, String value2) {
            addCriterion("courseAttribute between", value1, value2, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andCourseattributeNotBetween(String value1, String value2) {
            addCriterion("courseAttribute not between", value1, value2, "courseattribute");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberIsNull() {
            addCriterion("alternativeCourseNumber is null");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberIsNotNull() {
            addCriterion("alternativeCourseNumber is not null");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberEqualTo(String value) {
            addCriterion("alternativeCourseNumber =", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberNotEqualTo(String value) {
            addCriterion("alternativeCourseNumber <>", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberGreaterThan(String value) {
            addCriterion("alternativeCourseNumber >", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberGreaterThanOrEqualTo(String value) {
            addCriterion("alternativeCourseNumber >=", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberLessThan(String value) {
            addCriterion("alternativeCourseNumber <", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberLessThanOrEqualTo(String value) {
            addCriterion("alternativeCourseNumber <=", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberLike(String value) {
            addCriterion("alternativeCourseNumber like", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberNotLike(String value) {
            addCriterion("alternativeCourseNumber not like", value, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberIn(List<String> values) {
            addCriterion("alternativeCourseNumber in", values, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberNotIn(List<String> values) {
            addCriterion("alternativeCourseNumber not in", values, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberBetween(String value1, String value2) {
            addCriterion("alternativeCourseNumber between", value1, value2, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenumberNotBetween(String value1, String value2) {
            addCriterion("alternativeCourseNumber not between", value1, value2, "alternativecoursenumber");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameIsNull() {
            addCriterion("alternativeCourseName is null");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameIsNotNull() {
            addCriterion("alternativeCourseName is not null");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameEqualTo(String value) {
            addCriterion("alternativeCourseName =", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameNotEqualTo(String value) {
            addCriterion("alternativeCourseName <>", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameGreaterThan(String value) {
            addCriterion("alternativeCourseName >", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameGreaterThanOrEqualTo(String value) {
            addCriterion("alternativeCourseName >=", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameLessThan(String value) {
            addCriterion("alternativeCourseName <", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameLessThanOrEqualTo(String value) {
            addCriterion("alternativeCourseName <=", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameLike(String value) {
            addCriterion("alternativeCourseName like", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameNotLike(String value) {
            addCriterion("alternativeCourseName not like", value, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameIn(List<String> values) {
            addCriterion("alternativeCourseName in", values, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameNotIn(List<String> values) {
            addCriterion("alternativeCourseName not in", values, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameBetween(String value1, String value2) {
            addCriterion("alternativeCourseName between", value1, value2, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andAlternativecoursenameNotBetween(String value1, String value2) {
            addCriterion("alternativeCourseName not between", value1, value2, "alternativecoursename");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreIsNull() {
            addCriterion("markOfScore is null");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreIsNotNull() {
            addCriterion("markOfScore is not null");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreEqualTo(String value) {
            addCriterion("markOfScore =", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreNotEqualTo(String value) {
            addCriterion("markOfScore <>", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreGreaterThan(String value) {
            addCriterion("markOfScore >", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreGreaterThanOrEqualTo(String value) {
            addCriterion("markOfScore >=", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreLessThan(String value) {
            addCriterion("markOfScore <", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreLessThanOrEqualTo(String value) {
            addCriterion("markOfScore <=", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreLike(String value) {
            addCriterion("markOfScore like", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreNotLike(String value) {
            addCriterion("markOfScore not like", value, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreIn(List<String> values) {
            addCriterion("markOfScore in", values, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreNotIn(List<String> values) {
            addCriterion("markOfScore not in", values, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreBetween(String value1, String value2) {
            addCriterion("markOfScore between", value1, value2, "markofscore");
            return (Criteria) this;
        }

        public Criteria andMarkofscoreNotBetween(String value1, String value2) {
            addCriterion("markOfScore not between", value1, value2, "markofscore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated do_not_delete_during_merge Sun May 17 09:53:32 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated Sun May 17 09:53:32 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}