package com.guohe.app.model;

public class SignIn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.signInId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Integer signInId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.createTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.isOverTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Integer isOverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.creator
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.year
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.timeLimit
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Integer timeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.name
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in.classes
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private String classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.signInId
     *
     * @return the value of sign_in.signInId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Integer getSignInId() {
        return signInId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.signInId
     *
     * @param signInId the value for sign_in.signInId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setSignInId(Integer signInId) {
        this.signInId = signInId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.createTime
     *
     * @return the value of sign_in.createTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.createTime
     *
     * @param createTime the value for sign_in.createTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.isOverTime
     *
     * @return the value of sign_in.isOverTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Integer getIsOverTime() {
        return isOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.isOverTime
     *
     * @param isOverTime the value for sign_in.isOverTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setIsOverTime(Integer isOverTime) {
        this.isOverTime = isOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.creator
     *
     * @return the value of sign_in.creator
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.creator
     *
     * @param creator the value for sign_in.creator
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.longitude
     *
     * @return the value of sign_in.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.longitude
     *
     * @param longitude the value for sign_in.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.latitude
     *
     * @return the value of sign_in.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.latitude
     *
     * @param latitude the value for sign_in.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.year
     *
     * @return the value of sign_in.year
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.year
     *
     * @param year the value for sign_in.year
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.timeLimit
     *
     * @return the value of sign_in.timeLimit
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Integer getTimeLimit() {
        return timeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.timeLimit
     *
     * @param timeLimit the value for sign_in.timeLimit
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setTimeLimit(Integer timeLimit) {
        this.timeLimit = timeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.name
     *
     * @return the value of sign_in.name
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.name
     *
     * @param name the value for sign_in.name
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in.classes
     *
     * @return the value of sign_in.classes
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in.classes
     *
     * @param classes the value for sign_in.classes
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }
}