package com.guohe.app.model;

public class SignData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.id
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.signId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Integer signId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.signTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Long signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.signed
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Integer signed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.stuNum
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private String stuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_data.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.id
     *
     * @return the value of sign_data.id
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.id
     *
     * @param id the value for sign_data.id
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.signId
     *
     * @return the value of sign_data.signId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.signId
     *
     * @param signId the value for sign_data.signId
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.signTime
     *
     * @return the value of sign_data.signTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Long getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.signTime
     *
     * @param signTime the value for sign_data.signTime
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setSignTime(Long signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.signed
     *
     * @return the value of sign_data.signed
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Integer getSigned() {
        return signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.signed
     *
     * @param signed the value for sign_data.signed
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setSigned(Integer signed) {
        this.signed = signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.stuNum
     *
     * @return the value of sign_data.stuNum
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.stuNum
     *
     * @param stuNum the value for sign_data.stuNum
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.longitude
     *
     * @return the value of sign_data.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.longitude
     *
     * @param longitude the value for sign_data.longitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_data.latitude
     *
     * @return the value of sign_data.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_data.latitude
     *
     * @param latitude the value for sign_data.latitude
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}