package com.guohe.app.model;

import java.util.Date;

public class StuInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.password
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.name
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.birthday
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.major
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.academy
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String academy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.class_num
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String class_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.identity_card_number
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String identity_card_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.sex
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.updated_time
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    private Date updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.uid
     *
     * @return the value of student_info.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.uid
     *
     * @param uid the value for student_info.uid
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.password
     *
     * @return the value of student_info.password
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.password
     *
     * @param password the value for student_info.password
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.name
     *
     * @return the value of student_info.name
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.name
     *
     * @param name the value for student_info.name
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.birthday
     *
     * @return the value of student_info.birthday
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.birthday
     *
     * @param birthday the value for student_info.birthday
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.major
     *
     * @return the value of student_info.major
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.major
     *
     * @param major the value for student_info.major
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.academy
     *
     * @return the value of student_info.academy
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.academy
     *
     * @param academy the value for student_info.academy
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.class_num
     *
     * @return the value of student_info.class_num
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getClass_num() {
        return class_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.class_num
     *
     * @param class_num the value for student_info.class_num
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setClass_num(String class_num) {
        this.class_num = class_num == null ? null : class_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.identity_card_number
     *
     * @return the value of student_info.identity_card_number
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getIdentity_card_number() {
        return identity_card_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.identity_card_number
     *
     * @param identity_card_number the value for student_info.identity_card_number
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setIdentity_card_number(String identity_card_number) {
        this.identity_card_number = identity_card_number == null ? null : identity_card_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.sex
     *
     * @return the value of student_info.sex
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.sex
     *
     * @param sex the value for student_info.sex
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.updated_time
     *
     * @return the value of student_info.updated_time
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public Date getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.updated_time
     *
     * @param updated_time the value for student_info.updated_time
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    public void setUpdated_time(Date updated_time) {
        this.updated_time = updated_time;
    }
}