package com.guohe.app.mapper;

import com.guohe.app.model.SignIn;
import com.guohe.app.model.SignInExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SignInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    long countByExample(SignInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int deleteByExample(SignInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int deleteByPrimaryKey(Integer signInId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int insert(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int insertSelective(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    List<SignIn> selectByExampleWithRowbounds(SignInExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    List<SignIn> selectByExample(SignInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    SignIn selectByPrimaryKey(Integer signInId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") SignIn record, @Param("example") SignInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByExample(@Param("record") SignIn record, @Param("example") SignInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByPrimaryKeySelective(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByPrimaryKey(SignIn record);
}