package com.guohe.app.mapper;

import com.guohe.app.model.SignData;
import com.guohe.app.model.SignDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SignDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    long countByExample(SignDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int deleteByExample(SignDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int insert(SignData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int insertSelective(SignData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    List<SignData> selectByExampleWithRowbounds(SignDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    List<SignData> selectByExample(SignDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    SignData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SignData record, @Param("example") SignDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int updateByExample(@Param("record") SignData record, @Param("example") SignDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int updateByPrimaryKeySelective(SignData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_data
     *
     * @mbg.generated Tue Aug 18 21:56:21 CST 2020
     */
    int updateByPrimaryKey(SignData record);
}