package com.guohe.app.mapper;

import com.guohe.app.model.StuInfo;
import com.guohe.app.model.StuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    long countByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int deleteByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int insert(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int insertSelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    List<StuInfo> selectByExampleWithRowbounds(StuInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    List<StuInfo> selectByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    StuInfo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") StuInfo record, @Param("example") StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByExample(@Param("record") StuInfo record, @Param("example") StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByPrimaryKeySelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbg.generated Wed Aug 19 15:59:53 CST 2020
     */
    int updateByPrimaryKey(StuInfo record);
}